### ISSUE TITLE
您好！能不能做成组件可选的配置模式，还有可不可以加上docker

### ISSUE THREAD

**Issue by kylinfedora** [soffchen/NanoPi-R2S#18]
您好！能不能做成组件可选的配置模式，还有可不可以加上docker
新手不知道可不可以这么做

**Comment by soffchen** [comment]
自己 fork 一下，修改一下 config 就可以哦

这个项目的目的是提供 actions 编译模板

**Comment by kylinfedora** [comment]
> 自己 fork 一下，修改一下 config 就可以哦
> 
> 这个项目的目的是提供 actions 编译模板
发现我修改了但是不生效
https://github.com/kylinfedora/NanoPi-R2S/blob/200324/r2s-rk3328-config
麻烦帮忙看下

**Comment by soffchen** [comment]
新 release 已增加 Docker
