### ISSUE TITLE
VPN Server

### ISSUE THREAD

**Issue by fanteral** [soffchen/NanoPi-R2S#19]
能不能加上VPN Server插件，OpenVPN还是用的少一些

**Comment by soffchen** [comment]
VPN Server 插件 指的是哪个？

**Comment by fanteral** [comment]
官方固件自带的VPN服务器，支持PPTP 、L2TP、IPsec等协议，好像是xl2tpd或者luci-app-ipsec-vpnd

**Comment by soffchen** [comment]
新 release 已添加 IPSec VPN
