### ISSUE TITLE
ipv6的问题 

### ISSUE THREAD

**Issue by dongzeqq** [soffchen/NanoPi-R2S#21]
我看路由有ipv6的地址 ,但是wan口还是分配一个本地ipv6地址 ,这是不对的,而且lan口没有分配ipv6地址,大神这是啥问题 ,麻烦啦

**Comment by soffchen** [comment]
官方禁掉了，可以参照这个 commit 自己改回去。

**Comment by dongzeqq** [comment]
> 官方禁掉了，可以参照这个 commit 自己改回去。

哪个提交 ? 还不休息哈哈 ,辛苦了

**Comment by soffchen** [comment]
https://github.com/friendlyarm/friendlywrt/commit/f092ca098e80c667b10cdd1dba328506a2673c1d

刚才没贴上 哈

**Comment by dongzeqq** [comment]
> [friendlyarm/friendlywrt@f092ca0](https://github.com/friendlyarm/friendlywrt/commit/f092ca098e80c667b10cdd1dba328506a2673c1d)
> 
> 刚才没贴上 哈

太感谢了

**Comment by trulynb** [comment]
跪求把ipv6的功能加回来
