### ISSUE TITLE
frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！

### ISSUE THREAD

**Issue by GunMoe** [soffchen/NanoPi-R2S#26]
frp服务 不管是不是开启TCP多路复用都启动失败  
各位大佬  咋回事呀....
 哪怕令牌输错  日志里也是这个报错...

**Comment by soffchen** [comment]
请检查是否跟服务器端版本是否一致？frp 版本要求还挺严的。

**Comment by GunMoe** [comment]
> 请检查是否跟服务器端版本是否一致？frp版本要求还挺严的。

好的  我试试

**Comment by GunMoe** [comment]
> > 请检查是否跟服务器端版本是否一致？frp版本要求还挺严的。
> 
> 好的我试试
