### ISSUE TITLE
备份能备份哪些数据

### ISSUE THREAD

**Issue by hunao0221** [soffchen/NanoPi-R2S#29]
看了下，又出了好几个新版，想更新一下。不知道能备份什么数据

**Comment by soffchen** [comment]
可以导出备份，也可以参考这个进行无损升级 https://github.com/soffchen/NanoPi-R2S/issues/10

另外，后面的固件都支持无损在线升级了。

**Comment by hunao0221** [comment]
thanks, 搞定了
