### ISSUE TITLE
通过LAN口进入后台提示不安全

### ISSUE THREAD

**Issue by nb5p** [soffchen/NanoPi-R2S#3]
![CleanShot 2020-02-23 at 14 00 56](https://user-images.githubusercontent.com/2098464/75104524-0b449e80-5645-11ea-888f-3d1056374afc.png)

**Comment by soffchen** [comment]
正在编译的版本已经关掉了自动跳转 https，后面再刷即可。

也可以通过修改现有文件`/etc/config/uhttpd`，将`option redirect_https	1`注释掉或者删除，重启即可。

**Comment by nb5p** [comment]
刚输入了新版的固件，已经可以正常工作了。
还俩个问题，如何开启从WAN口访问后台？
为什么编译的固件限制了1G的大小，我去官方发布的FriendlyWrt下载也是解压后1G

**Comment by soffchen** [comment]
WAN 口访问默认就是打开的哦，你试试。

**Comment by nb5p** [comment]
我试过了，跳转到`/cgi-bin/luci`会被拒绝

**Comment by soffchen** [comment]
亲测没问题，再试试哦。
