### ISSUE TITLE
Indexcache is not sane! stack traceback:

### ISSUE THREAD

**Issue by hunao0221** [soffchen/NanoPi-R2S#35]
经常出现这个问题啊，不光后台进不去去，连网都没有了。请问有解决办法吗？

**Comment by soffchen** [comment]
```rm -r /tmp/luci-indexcache``` 试试

是不是换主题了？

**Comment by hunao0221** [comment]
> `rm -r /tmp/luci-indexcache` 试试
> 
> 是不是换主题了？

嗯，之前用的是极光那个主题，后来就出现了这个问题，网上搜了下就换成了默认主题，但还是出现了这个情况

**Comment by soffchen** [comment]
```rm -r /tmp/luci-indexcache```

反正是主题的问题了，你好蛋疼哦 :)
