### ISSUE TITLE
尝试安装SQM之后提示内部错误

### ISSUE THREAD

**Issue by Fover23** [soffchen/NanoPi-R2S#36]
尝试安装luci-app-sqm之后，luci管理界面出现了一些错误。
提示internal error 500的一个错误

作者有独立的clash ipk和openclash ipk地址提供么？我想用原生的，找了半天没有找到对应架构的ipk，因为我需要sqm来管理我的整个网络，做一个qos。要不然在多人竞争使用的时候，网络的状况不太理想

**Comment by soffchen** [comment]
自己打开 CONFIG_PACKAGE_luci-app-sqm  然后重新编译嘛，这个项目的主要目的是提供编译模板，而不是提供固件哦。

**Comment by Fover23** [comment]
啊哈，好的～
