### ISSUE TITLE
如何开启adguradhome这个插件

### ISSUE THREAD

**Issue by qidong364482611** [soffchen/NanoPi-R2S#40]
萌新 不太懂 ，希望热心的网友告诉一下

**Comment by 02015678** [comment]
去[这里](https://github.com/songchenwen/nanopi-r2s-opkg-feeds/blob/master/packages/luci-app-adguardhome_1.8-11_all.ipk)下载安装即可。

如果需要其他package，参见这个repo的说明
https://nanopi-r2s-opkg-feeds.songchenwen.com/packages/

**Comment by soffchen** [comment]
楼上提供的安装方法，对于本 repo，可以修改 config ```CONFIG_PACKAGE_luci-app-adguardhome=y``` 进行编译即可。
