### ISSUE TITLE
关于系统-R2S刷机

### ISSUE THREAD

**Issue by hunao0221** [soffchen/NanoPi-R2S#42]
很抱歉上一条issues没描述清楚，手机党。
最近尝试使用这个功能升级一下ROM，但一直没找到正确的方式
它一直期望有个sd.img.gz的ROM文件，但是我下载了release的包，解压得到的是.zip,
我是否是需要再将.zip解压得到.img文件后，将.img压缩成.gz?

**Comment by soffchen** [comment]
没有装过本 ROM 的，直接下载 releases 的 zip 文件，解压得到 img 写 tf 卡。
装过本 ROM 的，直接下载 releases 的 zip 文件，左侧 系统里面在线升级。
