### ISSUE TITLE
请教开启adguardhome

### ISSUE THREAD

**Issue by eklim530** [soffchen/NanoPi-R2S#44]
请教soff老师及各位大神，请问若想开启adguardhome，是否在文件里把注释掉的CONFIG_PACKAGE_luci-app-adguardhome 改为CONFIG_PACKAGE_luci-app-adguardhome=y，然后编译即可，是这样吗？还需不需要在哪做其他修改？谢谢！

**Comment by soffchen** [comment]
对的，打开重新编译就行了。

**Comment by eklim530** [comment]
谢谢soff老师~

**Comment by soffchen** [comment]
明天新出一个版本默认把这个加进去

**Comment by soffchen** [comment]
https://github.com/soffchen/NanoPi-R2S/releases/tag/v20200816
