### ISSUE TITLE
内网无法通过域名+端口访问，外网可以

### ISSUE THREAD

**Issue by liangddyy** [soffchen/NanoPi-R2S#56]
https://www.right.com.cn/forum/thread-4030811-1-1.html
这里说很多固件都有这个问题，这个可以解决么？因为期望在内外网用同一套配置。

**Comment by soffchen** [comment]
你可以在内网 dnsmasq 上面，加一条静态记录，把域名指到内网 ip

**Comment by liangddyy** [comment]
嗯嗯，已经采用这种方法解决了。
