### ISSUE TITLE
建议使用diffconfig.sh生成配置文件

### ISSUE THREAD

**Issue by pwrliang** [soffchen/NanoPi-R2S#6]
Hi ，感谢你写的脚本，非常易懂和容易修改。有一点建议，可以使用./friendlywrt/scripts/diffconfig.sh这个脚本生成config文件，这样会使得config非常小，易于看出哪些配置发生了变化。

**Comment by soffchen** [comment]
保存完整 config 的目的是为了让大家 fork 之后可以自行打开任意配置，如果只是精简的话，又得一个一个去找补回来。

我会修改一下脚本，每次编译生成一个 config.diff 打包进去。
