### ISSUE TITLE
facetime无法接通，吃鸡无法连接游戏。

### ISSUE THREAD

**Issue by lixiangzhi0518** [soffchen/NanoPi-R2S#66]
tplink易展3250做主路由==》交换机==》mesh了六台1850 和 R2S旁路由关闭了DHCP。
需要联网的设备静态ip加主路由网关，翻墙什么都好，但是 facetime只要接通wifi就断掉 切换4G，吃鸡是能进入大厅，进不了游戏。
关掉openclash，或者直接连接tplink，没有问题。全局什么的设置全部默认。redir host， udp启用，armv8等等

**Comment by soffchen** [comment]
Release 里面的版本，OpenClash 其实是有问题的，没有起来，你确定起来了？Action 里面的修复了。

**Comment by lixiangzhi0518** [comment]
openclash没有起来，但是现在已经好了。facetime和手机不能玩和平精英的问题还是存在，好像跟udp有点关系，切换成redir host tun 混合模式可以吃鸡了，但是还是会不间断掉线。openclash里面设置全部默认。

**Comment by lixiangzhi0518** [comment]
openclash没有起来，但是最新的版本已经好了。facetime和手机不能玩和平精英的问题还是存在，好像跟udp有点关系，切换成redir host tun 混合模式可以吃鸡了，但是还是会不间断掉线。openclash里面设置全部默认。

**Comment by soffchen** [comment]
这个现象不一定是固件的问题了，你要不要试试 Hello World 或者  Passwall?

**Comment by lixiangzhi0518** [comment]
好的，我也不能确定是固件的问题，还在诊断中。百度上有类似提问，但出问题的人数偏少，我再找找看吧，谢谢！
