### ISSUE TITLE
新买的闪迪内存卡，刷了以后开机无法获取IP，进不去后台

### ISSUE THREAD

**Issue by gimgoo** [soffchen/NanoPi-R2S#68]
如题，新买的闪迪内存卡，刷了以后开机无法获取IP。一直都是16开头的那个内网地址，两个口换着插也一样。
但是系统的灯是正常的，风扇都是转的。

**Comment by soffchen** [comment]
换个软件再刷刷看

Windows 用: Rufus / balenaEtcher
macOS 用: balenaEtcher
