### ISSUE TITLE
希望添加luci-app-dockerman

### ISSUE THREAD

**Issue by DuskHub** [soffchen/NanoPi-R2S#7]
项目地址：https://github.com/lisaac/luci-app-dockerman
目前已经合并到Lean的代码里。
依赖：
luci-lib-docker
luci-lib-jsonc

**Comment by soffchen** [comment]
可以 fork 之后，把 `CONFIG_PACKAGE_luci-app-dockerman=y` 打开就好了哦

**Comment by mrlwei** [comment]
ssr plus能加么？

**Comment by soffchen** [comment]
> ssr plus能加么？

这个不是有吗？
