### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by xenstar** [soffchen/NanoPi-R2S#72]
1) Is there any easy way to update it? Or I have to download the zip file, then burn it in the memory card, then restore my settings in openwrt. 

Please let me know.

**Comment by soffchen** [comment]
There is an OTA tool called rs2 flasher in the System menu, please check it.

**Comment by soffchen** [comment]
You may also upload the img.zip file, and use `rom_flash` command to update it.

**Comment by xenstar** [comment]
> You may also upload the img.zip file, and use `rom_flash` command to update it.

This one I don't know, not good at coding.

**Comment by xenstar** [comment]
> There is an OTA tool called rs2 flasher in the System menu, please check it.

Yes I found that r2s flasher, so I just upload the zip file via r2s and it will automatically update right? Will my settings be gone?

**Comment by soffchen** [comment]
> > There is an OTA tool called rs2 flasher in the System menu, please check it.
> 
> Yes I found that r2s flasher, so I just upload the zip file via r2s and it will automatically update right? Will my settings be gone?

There is an option `Keep settings` checked by default.

**Comment by xenstar** [comment]
> > > There is an OTA tool called rs2 flasher in the System menu, please check it.
> > 
> > 
> > Yes I found that r2s flasher, so I just upload the zip file via r2s and it will automatically update right? Will my settings be gone?
> 
> There is an option `Keep settings` checked by default.

great. let me try that. Thanks for quick reply. Do you have any telegram group?

**Comment by xenstar** [comment]
<img width="733" alt="version" src="https://user-images.githubusercontent.com/55502651/107200434-a8553e80-6a32-11eb-8956-0827d66d2f21.png">


Is there any way to know if it's updated or not? because after the update, the page didn't reload.
