### ISSUE TITLE
有病毒？肉鸡

### ISSUE THREAD

**Issue by 1021683053** [soffchen/NanoPi-R2S#83]
![image](https://user-images.githubusercontent.com/7711802/109279686-05375e00-7855-11eb-81c0-6ad32ede5c1e.png)
![image](https://user-images.githubusercontent.com/7711802/109279815-2c8e2b00-7855-11eb-95d2-09b06e81c343.png)

**Comment by soffchen** [comment]
不知所云，有病上医院
