### ISSUE TITLE
trojan-go用不了

### ISSUE THREAD

**Issue by reformc** [soffchen/NanoPi-R2S#86]
刷机后用passwall添加trojan-go节点启动不了服务，还好go交叉编译很方便，我直接编译了个trojan-go传上去就可以用了。
gcc包也安装不了，提示libbfd is 364299 bytes, expecting 364302 bytes

**Comment by soffchen** [comment]
又是 upx 压缩的鬼

**Comment by klever1988** [comment]
ni'y

> 又是 upx 压缩的鬼

你可以使用make tools/upx/compile先行编译upx而不是引用系统的upx-ucl（系统版本的upx压缩会带来问题）

**Comment by soffchen** [comment]
> ni'y
> 
> > 又是 upx 压缩的鬼
> 
> 你可以使用make tools/upx/compile先行编译upx而不是引用系统的upx-ucl（系统版本的upx压缩会带来问题）

一语惊醒梦中人

**Comment by soffchen** [comment]
fixed
